// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `normalize_slashes`, `packs`, `visit_directory`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `OpenPack`, `PackIndexEntry`, `PackIndex`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`

Future<RustAssetCatalog> scanAssets({required String rootPath}) =>
    RustLib.instance.api.crateApiAssetsScanAssets(rootPath: rootPath);

Future<RustPackCatalog> openSakiPack({required String path}) =>
    RustLib.instance.api.crateApiAssetsOpenSakiPack(path: path);

Future<Uint8List> readSakiPackEntry({
  required BigInt handle,
  required String path,
}) => RustLib.instance.api.crateApiAssetsReadSakiPackEntry(
  handle: handle,
  path: path,
);

Future<bool> materializeSakiPackEntry({
  required BigInt handle,
  required String path,
  required String outputPath,
}) => RustLib.instance.api.crateApiAssetsMaterializeSakiPackEntry(
  handle: handle,
  path: path,
  outputPath: outputPath,
);

Future<bool> closeSakiPack({required BigInt handle}) =>
    RustLib.instance.api.crateApiAssetsCloseSakiPack(handle: handle);

class RustAssetCatalog {
  final String rootPath;
  final List<RustAssetEntry> entries;
  final BigInt elapsedMicros;

  const RustAssetCatalog({
    required this.rootPath,
    required this.entries,
    required this.elapsedMicros,
  });

  @override
  int get hashCode =>
      rootPath.hashCode ^ entries.hashCode ^ elapsedMicros.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustAssetCatalog &&
          runtimeType == other.runtimeType &&
          rootPath == other.rootPath &&
          entries == other.entries &&
          elapsedMicros == other.elapsedMicros;
}

class RustAssetEntry {
  final String relativePath;
  final String absolutePath;
  final String fileName;
  final String stem;
  final String extension_;
  final BigInt size;
  final PlatformInt64 modifiedMillis;

  const RustAssetEntry({
    required this.relativePath,
    required this.absolutePath,
    required this.fileName,
    required this.stem,
    required this.extension_,
    required this.size,
    required this.modifiedMillis,
  });

  @override
  int get hashCode =>
      relativePath.hashCode ^
      absolutePath.hashCode ^
      fileName.hashCode ^
      stem.hashCode ^
      extension_.hashCode ^
      size.hashCode ^
      modifiedMillis.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustAssetEntry &&
          runtimeType == other.runtimeType &&
          relativePath == other.relativePath &&
          absolutePath == other.absolutePath &&
          fileName == other.fileName &&
          stem == other.stem &&
          extension_ == other.extension_ &&
          size == other.size &&
          modifiedMillis == other.modifiedMillis;
}

class RustPackCatalog {
  final BigInt handle;
  final String path;
  final List<RustPackEntry> entries;

  const RustPackCatalog({
    required this.handle,
    required this.path,
    required this.entries,
  });

  @override
  int get hashCode => handle.hashCode ^ path.hashCode ^ entries.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustPackCatalog &&
          runtimeType == other.runtimeType &&
          handle == other.handle &&
          path == other.path &&
          entries == other.entries;
}

class RustPackEntry {
  final String path;
  final BigInt offset;
  final BigInt length;
  final bool text;
  final String? sha256;

  const RustPackEntry({
    required this.path,
    required this.offset,
    required this.length,
    required this.text,
    this.sha256,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      offset.hashCode ^
      length.hashCode ^
      text.hashCode ^
      sha256.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustPackEntry &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          offset == other.offset &&
          length == other.length &&
          text == other.text &&
          sha256 == other.sha256;
}
