// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `inspect_one`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

Future<List<RustImageMetadata>> inspectImageFiles({
  required List<String> paths,
}) => RustLib.instance.api.crateApiImagesInspectImageFiles(paths: paths);

class RustImageMetadata {
  final String path;
  final int width;
  final int height;
  final BigInt decodedRgbaBytes;
  final BigInt fileBytes;
  final String format;
  final String? error;

  const RustImageMetadata({
    required this.path,
    required this.width,
    required this.height,
    required this.decodedRgbaBytes,
    required this.fileBytes,
    required this.format,
    this.error,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      width.hashCode ^
      height.hashCode ^
      decodedRgbaBytes.hashCode ^
      fileBytes.hashCode ^
      format.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustImageMetadata &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          width == other.width &&
          height == other.height &&
          decodedRgbaBytes == other.decodedRgbaBytes &&
          fileBytes == other.fileBytes &&
          format == other.format &&
          error == other.error;
}
