// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Ask the platform allocator to return unused native pages to the OS.
///
/// macOS keeps freed pages in malloc zones for fast reuse. Those pages are no
/// longer live game objects, but they remain charged to `phys_footprint` until
/// pressure relief runs.
BigInt releaseUnusedNativeMemory() =>
    RustLib.instance.api.crateApiMemoryReleaseUnusedNativeMemory();
