// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `parse_existing`, `read_i32`, `states`, `write_snapshot`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ReadState`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

Future<RustReadStateSnapshot> readStateOpen({required String path}) =>
    RustLib.instance.api.crateApiReadStateReadStateOpen(path: path);

Future<bool> readStateMark({
  required BigInt handle,
  required PlatformInt64 stableHash,
}) => RustLib.instance.api.crateApiReadStateReadStateMark(
  handle: handle,
  stableHash: stableHash,
);

Future<bool> readStateFlush({required BigInt handle}) =>
    RustLib.instance.api.crateApiReadStateReadStateFlush(handle: handle);

Future<bool> readStateReplace({
  required BigInt handle,
  required Int64List stableHashes,
  required List<int> legacyHashes,
}) => RustLib.instance.api.crateApiReadStateReadStateReplace(
  handle: handle,
  stableHashes: stableHashes,
  legacyHashes: legacyHashes,
);

Future<bool> readStateClear({required BigInt handle}) =>
    RustLib.instance.api.crateApiReadStateReadStateClear(handle: handle);

Future<bool> readStateClose({required BigInt handle}) =>
    RustLib.instance.api.crateApiReadStateReadStateClose(handle: handle);

class RustReadStateSnapshot {
  final BigInt handle;
  final Int64List stableHashes;
  final Int32List legacyHashes;
  final bool migratedLegacyFile;

  const RustReadStateSnapshot({
    required this.handle,
    required this.stableHashes,
    required this.legacyHashes,
    required this.migratedLegacyFile,
  });

  @override
  int get hashCode =>
      handle.hashCode ^
      stableHashes.hashCode ^
      legacyHashes.hashCode ^
      migratedLegacyFile.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustReadStateSnapshot &&
          runtimeType == other.runtimeType &&
          handle == other.handle &&
          stableHashes == other.stableHashes &&
          legacyHashes == other.legacyHashes &&
          migratedLegacyFile == other.migratedLegacyFile;
}
