// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `chapter_identity`, `estimate_bytes`, `runtimes`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CompactRuntime`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

Future<RustRuntimeIndex> buildRuntimeIndex({
  required List<RustRuntimeNode> nodes,
}) => RustLib.instance.api.crateApiRuntimeIndexBuildRuntimeIndex(nodes: nodes);

RustMenuSeekResult runtimeSeekMenu({
  required BigInt handle,
  required int startIndex,
  required Map<String, bool> boolVariables,
  required int maxSteps,
}) => RustLib.instance.api.crateApiRuntimeIndexRuntimeSeekMenu(
  handle: handle,
  startIndex: startIndex,
  boolVariables: boolVariables,
  maxSteps: maxSteps,
);

bool closeScriptRuntime({required BigInt handle}) =>
    RustLib.instance.api.crateApiRuntimeIndexCloseScriptRuntime(handle: handle);

class RustMenuSeekResult {
  final bool found;
  final int? menuIndex;
  final List<RustRuntimePrompt> prompts;
  final int visited;

  const RustMenuSeekResult({
    required this.found,
    this.menuIndex,
    required this.prompts,
    required this.visited,
  });

  @override
  int get hashCode =>
      found.hashCode ^ menuIndex.hashCode ^ prompts.hashCode ^ visited.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustMenuSeekResult &&
          runtimeType == other.runtimeType &&
          found == other.found &&
          menuIndex == other.menuIndex &&
          prompts == other.prompts &&
          visited == other.visited;
}

class RustRuntimeChoice {
  final String text;
  final String targetLabel;

  const RustRuntimeChoice({required this.text, required this.targetLabel});

  @override
  int get hashCode => text.hashCode ^ targetLabel.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustRuntimeChoice &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          targetLabel == other.targetLabel;
}

class RustRuntimeFlowNode {
  final String id;
  final String label;
  final String kind;
  final String displayName;
  final int scriptIndex;
  final String? chapterName;
  final String? parentId;
  final List<String> childIds;
  final String? branchText;
  final List<String> parentIds;

  const RustRuntimeFlowNode({
    required this.id,
    required this.label,
    required this.kind,
    required this.displayName,
    required this.scriptIndex,
    this.chapterName,
    this.parentId,
    required this.childIds,
    this.branchText,
    required this.parentIds,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      label.hashCode ^
      kind.hashCode ^
      displayName.hashCode ^
      scriptIndex.hashCode ^
      chapterName.hashCode ^
      parentId.hashCode ^
      childIds.hashCode ^
      branchText.hashCode ^
      parentIds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustRuntimeFlowNode &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label &&
          kind == other.kind &&
          displayName == other.displayName &&
          scriptIndex == other.scriptIndex &&
          chapterName == other.chapterName &&
          parentId == other.parentId &&
          childIds == other.childIds &&
          branchText == other.branchText &&
          parentIds == other.parentIds;
}

class RustRuntimeIndex {
  final BigInt handle;
  final List<RustRuntimeLabelIndex> labels;
  final List<RustRuntimeFlowNode> flowNodes;
  final List<String> rootIds;
  final BigInt compactBytes;
  final BigInt elapsedMicros;
  final List<String> conditionVariables;

  const RustRuntimeIndex({
    required this.handle,
    required this.labels,
    required this.flowNodes,
    required this.rootIds,
    required this.compactBytes,
    required this.elapsedMicros,
    required this.conditionVariables,
  });

  @override
  int get hashCode =>
      handle.hashCode ^
      labels.hashCode ^
      flowNodes.hashCode ^
      rootIds.hashCode ^
      compactBytes.hashCode ^
      elapsedMicros.hashCode ^
      conditionVariables.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustRuntimeIndex &&
          runtimeType == other.runtimeType &&
          handle == other.handle &&
          labels == other.labels &&
          flowNodes == other.flowNodes &&
          rootIds == other.rootIds &&
          compactBytes == other.compactBytes &&
          elapsedMicros == other.elapsedMicros &&
          conditionVariables == other.conditionVariables;
}

class RustRuntimeLabelIndex {
  final String label;
  final int scriptIndex;

  const RustRuntimeLabelIndex({required this.label, required this.scriptIndex});

  @override
  int get hashCode => label.hashCode ^ scriptIndex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustRuntimeLabelIndex &&
          runtimeType == other.runtimeType &&
          label == other.label &&
          scriptIndex == other.scriptIndex;
}

class RustRuntimeNode {
  final int scriptIndex;
  final String kind;
  final String? value;
  final String? secondary;
  final String? dialogueTag;
  final String? sourceFile;
  final int? sourceLine;
  final String? conditionVariable;
  final bool? conditionValue;
  final List<RustRuntimeChoice> choices;

  const RustRuntimeNode({
    required this.scriptIndex,
    required this.kind,
    this.value,
    this.secondary,
    this.dialogueTag,
    this.sourceFile,
    this.sourceLine,
    this.conditionVariable,
    this.conditionValue,
    required this.choices,
  });

  @override
  int get hashCode =>
      scriptIndex.hashCode ^
      kind.hashCode ^
      value.hashCode ^
      secondary.hashCode ^
      dialogueTag.hashCode ^
      sourceFile.hashCode ^
      sourceLine.hashCode ^
      conditionVariable.hashCode ^
      conditionValue.hashCode ^
      choices.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustRuntimeNode &&
          runtimeType == other.runtimeType &&
          scriptIndex == other.scriptIndex &&
          kind == other.kind &&
          value == other.value &&
          secondary == other.secondary &&
          dialogueTag == other.dialogueTag &&
          sourceFile == other.sourceFile &&
          sourceLine == other.sourceLine &&
          conditionVariable == other.conditionVariable &&
          conditionValue == other.conditionValue &&
          choices == other.choices;
}

class RustRuntimePrompt {
  final String dialogue;
  final String? speaker;
  final String? dialogueTag;
  final int scriptIndex;
  final String? sourceFile;
  final int? sourceLine;

  const RustRuntimePrompt({
    required this.dialogue,
    this.speaker,
    this.dialogueTag,
    required this.scriptIndex,
    this.sourceFile,
    this.sourceLine,
  });

  @override
  int get hashCode =>
      dialogue.hashCode ^
      speaker.hashCode ^
      dialogueTag.hashCode ^
      scriptIndex.hashCode ^
      sourceFile.hashCode ^
      sourceLine.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustRuntimePrompt &&
          runtimeType == other.runtimeType &&
          dialogue == other.dialogue &&
          speaker == other.speaker &&
          dialogueTag == other.dialogueTag &&
          scriptIndex == other.scriptIndex &&
          sourceFile == other.sourceFile &&
          sourceLine == other.sourceLine;
}
