// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `atomic_write`, `bool`, `character`, `collection`, `current_node`, `decode_header`, `decode`, `exact`, `game_state_preview`, `game_state`, `i32`, `i64`, `length`, `new`, `nullable_string`, `nvl`, `position`, `remaining`, `skip_nullable_bytes`, `snapshot`, `string`, `u8`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Reader`, `SavePreview`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`

Future<RustDecodedSave> decodeSaveBytes({required List<int> data}) =>
    RustLib.instance.api.crateApiSaveCodecDecodeSaveBytes(data: data);

Future<RustDecodedSave> readSaveFile({required String path}) =>
    RustLib.instance.api.crateApiSaveCodecReadSaveFile(path: path);

Future<RustSaveMetadata> writeSaveFile({
  required String path,
  required List<int> data,
}) =>
    RustLib.instance.api.crateApiSaveCodecWriteSaveFile(path: path, data: data);

Future<RustSaveHeaderScan> scanSaveHeaders({
  required String directory,
  required PlatformInt64 startSlotId,
  required PlatformInt64 endSlotId,
}) => RustLib.instance.api.crateApiSaveCodecScanSaveHeaders(
  directory: directory,
  startSlotId: startSlotId,
  endSlotId: endSlotId,
);

class RustDecodedSave {
  final RustSaveMetadata metadata;
  final Uint8List data;

  const RustDecodedSave({required this.metadata, required this.data});

  @override
  int get hashCode => metadata.hashCode ^ data.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustDecodedSave &&
          runtimeType == other.runtimeType &&
          metadata == other.metadata &&
          data == other.data;
}

class RustSaveHeader {
  final PlatformInt64 id;
  final int version;
  final PlatformInt64 saveTimeMillis;
  final String currentScript;
  final String dialoguePreview;
  final String filePath;
  final PlatformInt64? screenshotOffset;
  final PlatformInt64? screenshotLength;
  final bool isLocked;
  final int scriptIndex;
  final String previewKind;
  final String? previewSpeaker;
  final String? previewText;
  final List<String> previewChoices;

  const RustSaveHeader({
    required this.id,
    required this.version,
    required this.saveTimeMillis,
    required this.currentScript,
    required this.dialoguePreview,
    required this.filePath,
    this.screenshotOffset,
    this.screenshotLength,
    required this.isLocked,
    required this.scriptIndex,
    required this.previewKind,
    this.previewSpeaker,
    this.previewText,
    required this.previewChoices,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      version.hashCode ^
      saveTimeMillis.hashCode ^
      currentScript.hashCode ^
      dialoguePreview.hashCode ^
      filePath.hashCode ^
      screenshotOffset.hashCode ^
      screenshotLength.hashCode ^
      isLocked.hashCode ^
      scriptIndex.hashCode ^
      previewKind.hashCode ^
      previewSpeaker.hashCode ^
      previewText.hashCode ^
      previewChoices.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustSaveHeader &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          version == other.version &&
          saveTimeMillis == other.saveTimeMillis &&
          currentScript == other.currentScript &&
          dialoguePreview == other.dialoguePreview &&
          filePath == other.filePath &&
          screenshotOffset == other.screenshotOffset &&
          screenshotLength == other.screenshotLength &&
          isLocked == other.isLocked &&
          scriptIndex == other.scriptIndex &&
          previewKind == other.previewKind &&
          previewSpeaker == other.previewSpeaker &&
          previewText == other.previewText &&
          previewChoices == other.previewChoices;
}

class RustSaveHeaderScan {
  final List<RustSaveHeader> slots;
  final List<String> invalidFiles;
  final BigInt elapsedMicros;

  const RustSaveHeaderScan({
    required this.slots,
    required this.invalidFiles,
    required this.elapsedMicros,
  });

  @override
  int get hashCode =>
      slots.hashCode ^ invalidFiles.hashCode ^ elapsedMicros.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustSaveHeaderScan &&
          runtimeType == other.runtimeType &&
          slots == other.slots &&
          invalidFiles == other.invalidFiles &&
          elapsedMicros == other.elapsedMicros;
}

class RustSaveMetadata {
  final int version;
  final PlatformInt64 id;
  final PlatformInt64 saveTimeMillis;
  final String currentScript;
  final String dialoguePreview;
  final BigInt? screenshotOffset;
  final BigInt? screenshotLength;
  final bool isLocked;
  final int scriptIndex;

  const RustSaveMetadata({
    required this.version,
    required this.id,
    required this.saveTimeMillis,
    required this.currentScript,
    required this.dialoguePreview,
    this.screenshotOffset,
    this.screenshotLength,
    required this.isLocked,
    required this.scriptIndex,
  });

  @override
  int get hashCode =>
      version.hashCode ^
      id.hashCode ^
      saveTimeMillis.hashCode ^
      currentScript.hashCode ^
      dialoguePreview.hashCode ^
      screenshotOffset.hashCode ^
      screenshotLength.hashCode ^
      isLocked.hashCode ^
      scriptIndex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustSaveMetadata &&
          runtimeType == other.runtimeType &&
          version == other.version &&
          id == other.id &&
          saveTimeMillis == other.saveTimeMillis &&
          currentScript == other.currentScript &&
          dialoguePreview == other.dialoguePreview &&
          screenshotOffset == other.screenshotOffset &&
          screenshotLength == other.screenshotLength &&
          isLocked == other.isLocked &&
          scriptIndex == other.scriptIndex;
}
