// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `analyse`, `first_argument`, `strip_comment`, `visit`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `SourceAnalysis`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

Future<RustScriptCompileResult> compileSksSources({
  required List<RustScriptSource> sources,
}) => RustLib.instance.api.crateApiScriptsCompileSksSources(sources: sources);

class RustScriptCompileResult {
  final String mergedSource;
  final List<String> orderedFiles;
  final List<RustScriptLabel> labels;
  final List<RustScriptReference> references;
  final List<RustScriptDiagnostic> diagnostics;
  final BigInt elapsedMicros;

  const RustScriptCompileResult({
    required this.mergedSource,
    required this.orderedFiles,
    required this.labels,
    required this.references,
    required this.diagnostics,
    required this.elapsedMicros,
  });

  @override
  int get hashCode =>
      mergedSource.hashCode ^
      orderedFiles.hashCode ^
      labels.hashCode ^
      references.hashCode ^
      diagnostics.hashCode ^
      elapsedMicros.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustScriptCompileResult &&
          runtimeType == other.runtimeType &&
          mergedSource == other.mergedSource &&
          orderedFiles == other.orderedFiles &&
          labels == other.labels &&
          references == other.references &&
          diagnostics == other.diagnostics &&
          elapsedMicros == other.elapsedMicros;
}

class RustScriptDiagnostic {
  final String severity;
  final String message;
  final String fileName;
  final int sourceLine;

  const RustScriptDiagnostic({
    required this.severity,
    required this.message,
    required this.fileName,
    required this.sourceLine,
  });

  @override
  int get hashCode =>
      severity.hashCode ^
      message.hashCode ^
      fileName.hashCode ^
      sourceLine.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustScriptDiagnostic &&
          runtimeType == other.runtimeType &&
          severity == other.severity &&
          message == other.message &&
          fileName == other.fileName &&
          sourceLine == other.sourceLine;
}

class RustScriptLabel {
  final String label;
  final String fileName;
  final int sourceLine;

  const RustScriptLabel({
    required this.label,
    required this.fileName,
    required this.sourceLine,
  });

  @override
  int get hashCode => label.hashCode ^ fileName.hashCode ^ sourceLine.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustScriptLabel &&
          runtimeType == other.runtimeType &&
          label == other.label &&
          fileName == other.fileName &&
          sourceLine == other.sourceLine;
}

class RustScriptReference {
  final String kind;
  final String value;
  final String fileName;
  final int sourceLine;

  const RustScriptReference({
    required this.kind,
    required this.value,
    required this.fileName,
    required this.sourceLine,
  });

  @override
  int get hashCode =>
      kind.hashCode ^ value.hashCode ^ fileName.hashCode ^ sourceLine.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustScriptReference &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          value == other.value &&
          fileName == other.fileName &&
          sourceLine == other.sourceLine;
}

class RustScriptSource {
  final String fileName;
  final String content;

  const RustScriptSource({required this.fileName, required this.content});

  @override
  int get hashCode => fileName.hashCode ^ content.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustScriptSource &&
          runtimeType == other.runtimeType &&
          fileName == other.fileName &&
          content == other.content;
}
