// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/assets.dart';
import 'api/history_codec.dart';
import 'api/images.dart';
import 'api/read_state.dart';
import 'api/runtime_index.dart';
import 'api/save_codec.dart';
import 'api/scripts.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  Map<String, bool> dco_decode_Map_String_bool_None(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_i_32_loose(dynamic raw);

  @protected
  Int32List dco_decode_list_prim_i_32_strict(dynamic raw);

  @protected
  Int64List dco_decode_list_prim_i_64_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(String, bool)> dco_decode_list_record_string_bool(dynamic raw);

  @protected
  List<RustAssetEntry> dco_decode_list_rust_asset_entry(dynamic raw);

  @protected
  List<RustImageMetadata> dco_decode_list_rust_image_metadata(dynamic raw);

  @protected
  List<RustPackEntry> dco_decode_list_rust_pack_entry(dynamic raw);

  @protected
  List<RustRuntimeChoice> dco_decode_list_rust_runtime_choice(dynamic raw);

  @protected
  List<RustRuntimeFlowNode> dco_decode_list_rust_runtime_flow_node(dynamic raw);

  @protected
  List<RustRuntimeLabelIndex> dco_decode_list_rust_runtime_label_index(
    dynamic raw,
  );

  @protected
  List<RustRuntimeNode> dco_decode_list_rust_runtime_node(dynamic raw);

  @protected
  List<RustRuntimePrompt> dco_decode_list_rust_runtime_prompt(dynamic raw);

  @protected
  List<RustSaveHeader> dco_decode_list_rust_save_header(dynamic raw);

  @protected
  List<RustScriptDiagnostic> dco_decode_list_rust_script_diagnostic(
    dynamic raw,
  );

  @protected
  List<RustScriptLabel> dco_decode_list_rust_script_label(dynamic raw);

  @protected
  List<RustScriptReference> dco_decode_list_rust_script_reference(dynamic raw);

  @protected
  List<RustScriptSource> dco_decode_list_rust_script_source(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  (String, bool) dco_decode_record_string_bool(dynamic raw);

  @protected
  RustAssetCatalog dco_decode_rust_asset_catalog(dynamic raw);

  @protected
  RustAssetEntry dco_decode_rust_asset_entry(dynamic raw);

  @protected
  RustDecodedSave dco_decode_rust_decoded_save(dynamic raw);

  @protected
  RustImageMetadata dco_decode_rust_image_metadata(dynamic raw);

  @protected
  RustMenuSeekResult dco_decode_rust_menu_seek_result(dynamic raw);

  @protected
  RustPackCatalog dco_decode_rust_pack_catalog(dynamic raw);

  @protected
  RustPackEntry dco_decode_rust_pack_entry(dynamic raw);

  @protected
  RustReadStateSnapshot dco_decode_rust_read_state_snapshot(dynamic raw);

  @protected
  RustRuntimeChoice dco_decode_rust_runtime_choice(dynamic raw);

  @protected
  RustRuntimeFlowNode dco_decode_rust_runtime_flow_node(dynamic raw);

  @protected
  RustRuntimeIndex dco_decode_rust_runtime_index(dynamic raw);

  @protected
  RustRuntimeLabelIndex dco_decode_rust_runtime_label_index(dynamic raw);

  @protected
  RustRuntimeNode dco_decode_rust_runtime_node(dynamic raw);

  @protected
  RustRuntimePrompt dco_decode_rust_runtime_prompt(dynamic raw);

  @protected
  RustSaveHeader dco_decode_rust_save_header(dynamic raw);

  @protected
  RustSaveHeaderScan dco_decode_rust_save_header_scan(dynamic raw);

  @protected
  RustSaveMetadata dco_decode_rust_save_metadata(dynamic raw);

  @protected
  RustScriptCompileResult dco_decode_rust_script_compile_result(dynamic raw);

  @protected
  RustScriptDiagnostic dco_decode_rust_script_diagnostic(dynamic raw);

  @protected
  RustScriptLabel dco_decode_rust_script_label(dynamic raw);

  @protected
  RustScriptReference dco_decode_rust_script_reference(dynamic raw);

  @protected
  RustScriptSource dco_decode_rust_script_source(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  Map<String, bool> sse_decode_Map_String_bool_None(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_i_32_loose(SseDeserializer deserializer);

  @protected
  Int32List sse_decode_list_prim_i_32_strict(SseDeserializer deserializer);

  @protected
  Int64List sse_decode_list_prim_i_64_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(String, bool)> sse_decode_list_record_string_bool(
    SseDeserializer deserializer,
  );

  @protected
  List<RustAssetEntry> sse_decode_list_rust_asset_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<RustImageMetadata> sse_decode_list_rust_image_metadata(
    SseDeserializer deserializer,
  );

  @protected
  List<RustPackEntry> sse_decode_list_rust_pack_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<RustRuntimeChoice> sse_decode_list_rust_runtime_choice(
    SseDeserializer deserializer,
  );

  @protected
  List<RustRuntimeFlowNode> sse_decode_list_rust_runtime_flow_node(
    SseDeserializer deserializer,
  );

  @protected
  List<RustRuntimeLabelIndex> sse_decode_list_rust_runtime_label_index(
    SseDeserializer deserializer,
  );

  @protected
  List<RustRuntimeNode> sse_decode_list_rust_runtime_node(
    SseDeserializer deserializer,
  );

  @protected
  List<RustRuntimePrompt> sse_decode_list_rust_runtime_prompt(
    SseDeserializer deserializer,
  );

  @protected
  List<RustSaveHeader> sse_decode_list_rust_save_header(
    SseDeserializer deserializer,
  );

  @protected
  List<RustScriptDiagnostic> sse_decode_list_rust_script_diagnostic(
    SseDeserializer deserializer,
  );

  @protected
  List<RustScriptLabel> sse_decode_list_rust_script_label(
    SseDeserializer deserializer,
  );

  @protected
  List<RustScriptReference> sse_decode_list_rust_script_reference(
    SseDeserializer deserializer,
  );

  @protected
  List<RustScriptSource> sse_decode_list_rust_script_source(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  (String, bool) sse_decode_record_string_bool(SseDeserializer deserializer);

  @protected
  RustAssetCatalog sse_decode_rust_asset_catalog(SseDeserializer deserializer);

  @protected
  RustAssetEntry sse_decode_rust_asset_entry(SseDeserializer deserializer);

  @protected
  RustDecodedSave sse_decode_rust_decoded_save(SseDeserializer deserializer);

  @protected
  RustImageMetadata sse_decode_rust_image_metadata(
    SseDeserializer deserializer,
  );

  @protected
  RustMenuSeekResult sse_decode_rust_menu_seek_result(
    SseDeserializer deserializer,
  );

  @protected
  RustPackCatalog sse_decode_rust_pack_catalog(SseDeserializer deserializer);

  @protected
  RustPackEntry sse_decode_rust_pack_entry(SseDeserializer deserializer);

  @protected
  RustReadStateSnapshot sse_decode_rust_read_state_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  RustRuntimeChoice sse_decode_rust_runtime_choice(
    SseDeserializer deserializer,
  );

  @protected
  RustRuntimeFlowNode sse_decode_rust_runtime_flow_node(
    SseDeserializer deserializer,
  );

  @protected
  RustRuntimeIndex sse_decode_rust_runtime_index(SseDeserializer deserializer);

  @protected
  RustRuntimeLabelIndex sse_decode_rust_runtime_label_index(
    SseDeserializer deserializer,
  );

  @protected
  RustRuntimeNode sse_decode_rust_runtime_node(SseDeserializer deserializer);

  @protected
  RustRuntimePrompt sse_decode_rust_runtime_prompt(
    SseDeserializer deserializer,
  );

  @protected
  RustSaveHeader sse_decode_rust_save_header(SseDeserializer deserializer);

  @protected
  RustSaveHeaderScan sse_decode_rust_save_header_scan(
    SseDeserializer deserializer,
  );

  @protected
  RustSaveMetadata sse_decode_rust_save_metadata(SseDeserializer deserializer);

  @protected
  RustScriptCompileResult sse_decode_rust_script_compile_result(
    SseDeserializer deserializer,
  );

  @protected
  RustScriptDiagnostic sse_decode_rust_script_diagnostic(
    SseDeserializer deserializer,
  );

  @protected
  RustScriptLabel sse_decode_rust_script_label(SseDeserializer deserializer);

  @protected
  RustScriptReference sse_decode_rust_script_reference(
    SseDeserializer deserializer,
  );

  @protected
  RustScriptSource sse_decode_rust_script_source(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_Map_String_bool_None(
    Map<String, bool> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_i_32_loose(
    List<int> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_i_32_strict(
    Int32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_i_64_strict(
    Int64List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_bool(
    List<(String, bool)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_rust_asset_entry(
    List<RustAssetEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_rust_image_metadata(
    List<RustImageMetadata> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_rust_pack_entry(
    List<RustPackEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_rust_runtime_choice(
    List<RustRuntimeChoice> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_rust_runtime_flow_node(
    List<RustRuntimeFlowNode> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_rust_runtime_label_index(
    List<RustRuntimeLabelIndex> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_rust_runtime_node(
    List<RustRuntimeNode> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_rust_runtime_prompt(
    List<RustRuntimePrompt> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_rust_save_header(
    List<RustSaveHeader> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_rust_script_diagnostic(
    List<RustScriptDiagnostic> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_rust_script_label(
    List<RustScriptLabel> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_rust_script_reference(
    List<RustScriptReference> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_rust_script_source(
    List<RustScriptSource> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_record_string_bool(
    (String, bool) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rust_asset_catalog(
    RustAssetCatalog self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rust_asset_entry(
    RustAssetEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rust_decoded_save(
    RustDecodedSave self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rust_image_metadata(
    RustImageMetadata self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rust_menu_seek_result(
    RustMenuSeekResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rust_pack_catalog(
    RustPackCatalog self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rust_pack_entry(RustPackEntry self, SseSerializer serializer);

  @protected
  void sse_encode_rust_read_state_snapshot(
    RustReadStateSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rust_runtime_choice(
    RustRuntimeChoice self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rust_runtime_flow_node(
    RustRuntimeFlowNode self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rust_runtime_index(
    RustRuntimeIndex self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rust_runtime_label_index(
    RustRuntimeLabelIndex self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rust_runtime_node(
    RustRuntimeNode self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rust_runtime_prompt(
    RustRuntimePrompt self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rust_save_header(
    RustSaveHeader self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rust_save_header_scan(
    RustSaveHeaderScan self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rust_save_metadata(
    RustSaveMetadata self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rust_script_compile_result(
    RustScriptCompileResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rust_script_diagnostic(
    RustScriptDiagnostic self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rust_script_label(
    RustScriptLabel self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rust_script_reference(
    RustScriptReference self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rust_script_source(
    RustScriptSource self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
