// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/assets.dart';
import 'api/history_codec.dart';
import 'api/images.dart';
import 'api/memory.dart';
import 'api/read_state.dart';
import 'api/runtime_index.dart';
import 'api/save_codec.dart';
import 'api/scripts.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 1619407852;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'saki_native',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<RustRuntimeIndex> crateApiRuntimeIndexBuildRuntimeIndex({
    required List<RustRuntimeNode> nodes,
  });

  Future<bool> crateApiAssetsCloseSakiPack({required BigInt handle});

  bool crateApiRuntimeIndexCloseScriptRuntime({required BigInt handle});

  Future<RustScriptCompileResult> crateApiScriptsCompileSksSources({
    required List<RustScriptSource> sources,
  });

  Uint8List crateApiHistoryCodecCompressHistorySnapshot({
    required List<int> data,
  });

  Future<RustDecodedSave> crateApiSaveCodecDecodeSaveBytes({
    required List<int> data,
  });

  Uint8List crateApiHistoryCodecDecompressHistorySnapshot({
    required List<int> data,
  });

  Future<List<RustImageMetadata>> crateApiImagesInspectImageFiles({
    required List<String> paths,
  });

  Future<bool> crateApiAssetsMaterializeSakiPackEntry({
    required BigInt handle,
    required String path,
    required String outputPath,
  });

  Future<RustPackCatalog> crateApiAssetsOpenSakiPack({required String path});

  Future<Uint8List> crateApiAssetsReadSakiPackEntry({
    required BigInt handle,
    required String path,
  });

  Future<RustDecodedSave> crateApiSaveCodecReadSaveFile({required String path});

  Future<bool> crateApiReadStateReadStateClear({required BigInt handle});

  Future<bool> crateApiReadStateReadStateClose({required BigInt handle});

  Future<bool> crateApiReadStateReadStateFlush({required BigInt handle});

  Future<bool> crateApiReadStateReadStateMark({
    required BigInt handle,
    required PlatformInt64 stableHash,
  });

  Future<RustReadStateSnapshot> crateApiReadStateReadStateOpen({
    required String path,
  });

  Future<bool> crateApiReadStateReadStateReplace({
    required BigInt handle,
    required Int64List stableHashes,
    required List<int> legacyHashes,
  });

  BigInt crateApiMemoryReleaseUnusedNativeMemory();

  RustMenuSeekResult crateApiRuntimeIndexRuntimeSeekMenu({
    required BigInt handle,
    required int startIndex,
    required Map<String, bool> boolVariables,
    required int maxSteps,
  });

  Future<RustAssetCatalog> crateApiAssetsScanAssets({required String rootPath});

  Future<RustSaveHeaderScan> crateApiSaveCodecScanSaveHeaders({
    required String directory,
    required PlatformInt64 startSlotId,
    required PlatformInt64 endSlotId,
  });

  Future<RustSaveMetadata> crateApiSaveCodecWriteSaveFile({
    required String path,
    required List<int> data,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<RustRuntimeIndex> crateApiRuntimeIndexBuildRuntimeIndex({
    required List<RustRuntimeNode> nodes,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_rust_runtime_node(nodes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_rust_runtime_index,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRuntimeIndexBuildRuntimeIndexConstMeta,
        argValues: [nodes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRuntimeIndexBuildRuntimeIndexConstMeta =>
      const TaskConstMeta(
        debugName: "build_runtime_index",
        argNames: ["nodes"],
      );

  @override
  Future<bool> crateApiAssetsCloseSakiPack({required BigInt handle}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(handle, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAssetsCloseSakiPackConstMeta,
        argValues: [handle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAssetsCloseSakiPackConstMeta =>
      const TaskConstMeta(debugName: "close_saki_pack", argNames: ["handle"]);

  @override
  bool crateApiRuntimeIndexCloseScriptRuntime({required BigInt handle}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(handle, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRuntimeIndexCloseScriptRuntimeConstMeta,
        argValues: [handle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRuntimeIndexCloseScriptRuntimeConstMeta =>
      const TaskConstMeta(
        debugName: "close_script_runtime",
        argNames: ["handle"],
      );

  @override
  Future<RustScriptCompileResult> crateApiScriptsCompileSksSources({
    required List<RustScriptSource> sources,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_rust_script_source(sources, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_rust_script_compile_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiScriptsCompileSksSourcesConstMeta,
        argValues: [sources],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiScriptsCompileSksSourcesConstMeta =>
      const TaskConstMeta(
        debugName: "compile_sks_sources",
        argNames: ["sources"],
      );

  @override
  Uint8List crateApiHistoryCodecCompressHistorySnapshot({
    required List<int> data,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiHistoryCodecCompressHistorySnapshotConstMeta,
        argValues: [data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHistoryCodecCompressHistorySnapshotConstMeta =>
      const TaskConstMeta(
        debugName: "compress_history_snapshot",
        argNames: ["data"],
      );

  @override
  Future<RustDecodedSave> crateApiSaveCodecDecodeSaveBytes({
    required List<int> data,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_rust_decoded_save,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSaveCodecDecodeSaveBytesConstMeta,
        argValues: [data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSaveCodecDecodeSaveBytesConstMeta =>
      const TaskConstMeta(debugName: "decode_save_bytes", argNames: ["data"]);

  @override
  Uint8List crateApiHistoryCodecDecompressHistorySnapshot({
    required List<int> data,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiHistoryCodecDecompressHistorySnapshotConstMeta,
        argValues: [data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHistoryCodecDecompressHistorySnapshotConstMeta =>
      const TaskConstMeta(
        debugName: "decompress_history_snapshot",
        argNames: ["data"],
      );

  @override
  Future<List<RustImageMetadata>> crateApiImagesInspectImageFiles({
    required List<String> paths,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_String(paths, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_rust_image_metadata,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiImagesInspectImageFilesConstMeta,
        argValues: [paths],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImagesInspectImageFilesConstMeta =>
      const TaskConstMeta(
        debugName: "inspect_image_files",
        argNames: ["paths"],
      );

  @override
  Future<bool> crateApiAssetsMaterializeSakiPackEntry({
    required BigInt handle,
    required String path,
    required String outputPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(handle, serializer);
          sse_encode_String(path, serializer);
          sse_encode_String(outputPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAssetsMaterializeSakiPackEntryConstMeta,
        argValues: [handle, path, outputPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAssetsMaterializeSakiPackEntryConstMeta =>
      const TaskConstMeta(
        debugName: "materialize_saki_pack_entry",
        argNames: ["handle", "path", "outputPath"],
      );

  @override
  Future<RustPackCatalog> crateApiAssetsOpenSakiPack({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_rust_pack_catalog,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAssetsOpenSakiPackConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAssetsOpenSakiPackConstMeta =>
      const TaskConstMeta(debugName: "open_saki_pack", argNames: ["path"]);

  @override
  Future<Uint8List> crateApiAssetsReadSakiPackEntry({
    required BigInt handle,
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(handle, serializer);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAssetsReadSakiPackEntryConstMeta,
        argValues: [handle, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAssetsReadSakiPackEntryConstMeta =>
      const TaskConstMeta(
        debugName: "read_saki_pack_entry",
        argNames: ["handle", "path"],
      );

  @override
  Future<RustDecodedSave> crateApiSaveCodecReadSaveFile({
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_rust_decoded_save,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSaveCodecReadSaveFileConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSaveCodecReadSaveFileConstMeta =>
      const TaskConstMeta(debugName: "read_save_file", argNames: ["path"]);

  @override
  Future<bool> crateApiReadStateReadStateClear({required BigInt handle}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(handle, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiReadStateReadStateClearConstMeta,
        argValues: [handle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReadStateReadStateClearConstMeta =>
      const TaskConstMeta(debugName: "read_state_clear", argNames: ["handle"]);

  @override
  Future<bool> crateApiReadStateReadStateClose({required BigInt handle}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(handle, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiReadStateReadStateCloseConstMeta,
        argValues: [handle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReadStateReadStateCloseConstMeta =>
      const TaskConstMeta(debugName: "read_state_close", argNames: ["handle"]);

  @override
  Future<bool> crateApiReadStateReadStateFlush({required BigInt handle}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(handle, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiReadStateReadStateFlushConstMeta,
        argValues: [handle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReadStateReadStateFlushConstMeta =>
      const TaskConstMeta(debugName: "read_state_flush", argNames: ["handle"]);

  @override
  Future<bool> crateApiReadStateReadStateMark({
    required BigInt handle,
    required PlatformInt64 stableHash,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(handle, serializer);
          sse_encode_i_64(stableHash, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiReadStateReadStateMarkConstMeta,
        argValues: [handle, stableHash],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReadStateReadStateMarkConstMeta =>
      const TaskConstMeta(
        debugName: "read_state_mark",
        argNames: ["handle", "stableHash"],
      );

  @override
  Future<RustReadStateSnapshot> crateApiReadStateReadStateOpen({
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_rust_read_state_snapshot,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiReadStateReadStateOpenConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReadStateReadStateOpenConstMeta =>
      const TaskConstMeta(debugName: "read_state_open", argNames: ["path"]);

  @override
  Future<bool> crateApiReadStateReadStateReplace({
    required BigInt handle,
    required Int64List stableHashes,
    required List<int> legacyHashes,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(handle, serializer);
          sse_encode_list_prim_i_64_strict(stableHashes, serializer);
          sse_encode_list_prim_i_32_loose(legacyHashes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiReadStateReadStateReplaceConstMeta,
        argValues: [handle, stableHashes, legacyHashes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReadStateReadStateReplaceConstMeta =>
      const TaskConstMeta(
        debugName: "read_state_replace",
        argNames: ["handle", "stableHashes", "legacyHashes"],
      );

  @override
  BigInt crateApiMemoryReleaseUnusedNativeMemory() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMemoryReleaseUnusedNativeMemoryConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMemoryReleaseUnusedNativeMemoryConstMeta =>
      const TaskConstMeta(
        debugName: "release_unused_native_memory",
        argNames: [],
      );

  @override
  RustMenuSeekResult crateApiRuntimeIndexRuntimeSeekMenu({
    required BigInt handle,
    required int startIndex,
    required Map<String, bool> boolVariables,
    required int maxSteps,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(handle, serializer);
          sse_encode_u_32(startIndex, serializer);
          sse_encode_Map_String_bool_None(boolVariables, serializer);
          sse_encode_u_32(maxSteps, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_rust_menu_seek_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRuntimeIndexRuntimeSeekMenuConstMeta,
        argValues: [handle, startIndex, boolVariables, maxSteps],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRuntimeIndexRuntimeSeekMenuConstMeta =>
      const TaskConstMeta(
        debugName: "runtime_seek_menu",
        argNames: ["handle", "startIndex", "boolVariables", "maxSteps"],
      );

  @override
  Future<RustAssetCatalog> crateApiAssetsScanAssets({
    required String rootPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(rootPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_rust_asset_catalog,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAssetsScanAssetsConstMeta,
        argValues: [rootPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAssetsScanAssetsConstMeta =>
      const TaskConstMeta(debugName: "scan_assets", argNames: ["rootPath"]);

  @override
  Future<RustSaveHeaderScan> crateApiSaveCodecScanSaveHeaders({
    required String directory,
    required PlatformInt64 startSlotId,
    required PlatformInt64 endSlotId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(directory, serializer);
          sse_encode_i_64(startSlotId, serializer);
          sse_encode_i_64(endSlotId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_rust_save_header_scan,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSaveCodecScanSaveHeadersConstMeta,
        argValues: [directory, startSlotId, endSlotId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSaveCodecScanSaveHeadersConstMeta =>
      const TaskConstMeta(
        debugName: "scan_save_headers",
        argNames: ["directory", "startSlotId", "endSlotId"],
      );

  @override
  Future<RustSaveMetadata> crateApiSaveCodecWriteSaveFile({
    required String path,
    required List<int> data,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_list_prim_u_8_loose(data, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_rust_save_metadata,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSaveCodecWriteSaveFileConstMeta,
        argValues: [path, data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSaveCodecWriteSaveFileConstMeta =>
      const TaskConstMeta(
        debugName: "write_save_file",
        argNames: ["path", "data"],
      );

  @protected
  Map<String, bool> dco_decode_Map_String_bool_None(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Map.fromEntries(
      dco_decode_list_record_string_bool(raw).map((e) => MapEntry(e.$1, e.$2)),
    );
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<int> dco_decode_list_prim_i_32_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Int32List dco_decode_list_prim_i_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Int32List;
  }

  @protected
  Int64List dco_decode_list_prim_i_64_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeInt64List(raw);
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<(String, bool)> dco_decode_list_record_string_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_record_string_bool).toList();
  }

  @protected
  List<RustAssetEntry> dco_decode_list_rust_asset_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_rust_asset_entry).toList();
  }

  @protected
  List<RustImageMetadata> dco_decode_list_rust_image_metadata(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_rust_image_metadata).toList();
  }

  @protected
  List<RustPackEntry> dco_decode_list_rust_pack_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_rust_pack_entry).toList();
  }

  @protected
  List<RustRuntimeChoice> dco_decode_list_rust_runtime_choice(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_rust_runtime_choice).toList();
  }

  @protected
  List<RustRuntimeFlowNode> dco_decode_list_rust_runtime_flow_node(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_rust_runtime_flow_node)
        .toList();
  }

  @protected
  List<RustRuntimeLabelIndex> dco_decode_list_rust_runtime_label_index(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_rust_runtime_label_index)
        .toList();
  }

  @protected
  List<RustRuntimeNode> dco_decode_list_rust_runtime_node(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_rust_runtime_node).toList();
  }

  @protected
  List<RustRuntimePrompt> dco_decode_list_rust_runtime_prompt(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_rust_runtime_prompt).toList();
  }

  @protected
  List<RustSaveHeader> dco_decode_list_rust_save_header(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_rust_save_header).toList();
  }

  @protected
  List<RustScriptDiagnostic> dco_decode_list_rust_script_diagnostic(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_rust_script_diagnostic)
        .toList();
  }

  @protected
  List<RustScriptLabel> dco_decode_list_rust_script_label(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_rust_script_label).toList();
  }

  @protected
  List<RustScriptReference> dco_decode_list_rust_script_reference(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_rust_script_reference)
        .toList();
  }

  @protected
  List<RustScriptSource> dco_decode_list_rust_script_source(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_rust_script_source).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_bool(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  (String, bool) dco_decode_record_string_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (dco_decode_String(arr[0]), dco_decode_bool(arr[1]));
  }

  @protected
  RustAssetCatalog dco_decode_rust_asset_catalog(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return RustAssetCatalog(
      rootPath: dco_decode_String(arr[0]),
      entries: dco_decode_list_rust_asset_entry(arr[1]),
      elapsedMicros: dco_decode_u_64(arr[2]),
    );
  }

  @protected
  RustAssetEntry dco_decode_rust_asset_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return RustAssetEntry(
      relativePath: dco_decode_String(arr[0]),
      absolutePath: dco_decode_String(arr[1]),
      fileName: dco_decode_String(arr[2]),
      stem: dco_decode_String(arr[3]),
      extension_: dco_decode_String(arr[4]),
      size: dco_decode_u_64(arr[5]),
      modifiedMillis: dco_decode_i_64(arr[6]),
    );
  }

  @protected
  RustDecodedSave dco_decode_rust_decoded_save(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return RustDecodedSave(
      metadata: dco_decode_rust_save_metadata(arr[0]),
      data: dco_decode_list_prim_u_8_strict(arr[1]),
    );
  }

  @protected
  RustImageMetadata dco_decode_rust_image_metadata(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return RustImageMetadata(
      path: dco_decode_String(arr[0]),
      width: dco_decode_u_32(arr[1]),
      height: dco_decode_u_32(arr[2]),
      decodedRgbaBytes: dco_decode_u_64(arr[3]),
      fileBytes: dco_decode_u_64(arr[4]),
      format: dco_decode_String(arr[5]),
      error: dco_decode_opt_String(arr[6]),
    );
  }

  @protected
  RustMenuSeekResult dco_decode_rust_menu_seek_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return RustMenuSeekResult(
      found: dco_decode_bool(arr[0]),
      menuIndex: dco_decode_opt_box_autoadd_u_32(arr[1]),
      prompts: dco_decode_list_rust_runtime_prompt(arr[2]),
      visited: dco_decode_u_32(arr[3]),
    );
  }

  @protected
  RustPackCatalog dco_decode_rust_pack_catalog(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return RustPackCatalog(
      handle: dco_decode_u_64(arr[0]),
      path: dco_decode_String(arr[1]),
      entries: dco_decode_list_rust_pack_entry(arr[2]),
    );
  }

  @protected
  RustPackEntry dco_decode_rust_pack_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return RustPackEntry(
      path: dco_decode_String(arr[0]),
      offset: dco_decode_u_64(arr[1]),
      length: dco_decode_u_64(arr[2]),
      text: dco_decode_bool(arr[3]),
      sha256: dco_decode_opt_String(arr[4]),
    );
  }

  @protected
  RustReadStateSnapshot dco_decode_rust_read_state_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return RustReadStateSnapshot(
      handle: dco_decode_u_64(arr[0]),
      stableHashes: dco_decode_list_prim_i_64_strict(arr[1]),
      legacyHashes: dco_decode_list_prim_i_32_strict(arr[2]),
      migratedLegacyFile: dco_decode_bool(arr[3]),
    );
  }

  @protected
  RustRuntimeChoice dco_decode_rust_runtime_choice(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return RustRuntimeChoice(
      text: dco_decode_String(arr[0]),
      targetLabel: dco_decode_String(arr[1]),
    );
  }

  @protected
  RustRuntimeFlowNode dco_decode_rust_runtime_flow_node(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return RustRuntimeFlowNode(
      id: dco_decode_String(arr[0]),
      label: dco_decode_String(arr[1]),
      kind: dco_decode_String(arr[2]),
      displayName: dco_decode_String(arr[3]),
      scriptIndex: dco_decode_u_32(arr[4]),
      chapterName: dco_decode_opt_String(arr[5]),
      parentId: dco_decode_opt_String(arr[6]),
      childIds: dco_decode_list_String(arr[7]),
      branchText: dco_decode_opt_String(arr[8]),
      parentIds: dco_decode_list_String(arr[9]),
    );
  }

  @protected
  RustRuntimeIndex dco_decode_rust_runtime_index(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return RustRuntimeIndex(
      handle: dco_decode_u_64(arr[0]),
      labels: dco_decode_list_rust_runtime_label_index(arr[1]),
      flowNodes: dco_decode_list_rust_runtime_flow_node(arr[2]),
      rootIds: dco_decode_list_String(arr[3]),
      compactBytes: dco_decode_u_64(arr[4]),
      elapsedMicros: dco_decode_u_64(arr[5]),
      conditionVariables: dco_decode_list_String(arr[6]),
    );
  }

  @protected
  RustRuntimeLabelIndex dco_decode_rust_runtime_label_index(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return RustRuntimeLabelIndex(
      label: dco_decode_String(arr[0]),
      scriptIndex: dco_decode_u_32(arr[1]),
    );
  }

  @protected
  RustRuntimeNode dco_decode_rust_runtime_node(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return RustRuntimeNode(
      scriptIndex: dco_decode_u_32(arr[0]),
      kind: dco_decode_String(arr[1]),
      value: dco_decode_opt_String(arr[2]),
      secondary: dco_decode_opt_String(arr[3]),
      dialogueTag: dco_decode_opt_String(arr[4]),
      sourceFile: dco_decode_opt_String(arr[5]),
      sourceLine: dco_decode_opt_box_autoadd_u_32(arr[6]),
      conditionVariable: dco_decode_opt_String(arr[7]),
      conditionValue: dco_decode_opt_box_autoadd_bool(arr[8]),
      choices: dco_decode_list_rust_runtime_choice(arr[9]),
    );
  }

  @protected
  RustRuntimePrompt dco_decode_rust_runtime_prompt(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return RustRuntimePrompt(
      dialogue: dco_decode_String(arr[0]),
      speaker: dco_decode_opt_String(arr[1]),
      dialogueTag: dco_decode_opt_String(arr[2]),
      scriptIndex: dco_decode_u_32(arr[3]),
      sourceFile: dco_decode_opt_String(arr[4]),
      sourceLine: dco_decode_opt_box_autoadd_u_32(arr[5]),
    );
  }

  @protected
  RustSaveHeader dco_decode_rust_save_header(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 14)
      throw Exception('unexpected arr length: expect 14 but see ${arr.length}');
    return RustSaveHeader(
      id: dco_decode_i_64(arr[0]),
      version: dco_decode_i_32(arr[1]),
      saveTimeMillis: dco_decode_i_64(arr[2]),
      currentScript: dco_decode_String(arr[3]),
      dialoguePreview: dco_decode_String(arr[4]),
      filePath: dco_decode_String(arr[5]),
      screenshotOffset: dco_decode_opt_box_autoadd_i_64(arr[6]),
      screenshotLength: dco_decode_opt_box_autoadd_i_64(arr[7]),
      isLocked: dco_decode_bool(arr[8]),
      scriptIndex: dco_decode_i_32(arr[9]),
      previewKind: dco_decode_String(arr[10]),
      previewSpeaker: dco_decode_opt_String(arr[11]),
      previewText: dco_decode_opt_String(arr[12]),
      previewChoices: dco_decode_list_String(arr[13]),
    );
  }

  @protected
  RustSaveHeaderScan dco_decode_rust_save_header_scan(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return RustSaveHeaderScan(
      slots: dco_decode_list_rust_save_header(arr[0]),
      invalidFiles: dco_decode_list_String(arr[1]),
      elapsedMicros: dco_decode_u_64(arr[2]),
    );
  }

  @protected
  RustSaveMetadata dco_decode_rust_save_metadata(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return RustSaveMetadata(
      version: dco_decode_i_32(arr[0]),
      id: dco_decode_i_64(arr[1]),
      saveTimeMillis: dco_decode_i_64(arr[2]),
      currentScript: dco_decode_String(arr[3]),
      dialoguePreview: dco_decode_String(arr[4]),
      screenshotOffset: dco_decode_opt_box_autoadd_u_64(arr[5]),
      screenshotLength: dco_decode_opt_box_autoadd_u_64(arr[6]),
      isLocked: dco_decode_bool(arr[7]),
      scriptIndex: dco_decode_i_32(arr[8]),
    );
  }

  @protected
  RustScriptCompileResult dco_decode_rust_script_compile_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return RustScriptCompileResult(
      mergedSource: dco_decode_String(arr[0]),
      orderedFiles: dco_decode_list_String(arr[1]),
      labels: dco_decode_list_rust_script_label(arr[2]),
      references: dco_decode_list_rust_script_reference(arr[3]),
      diagnostics: dco_decode_list_rust_script_diagnostic(arr[4]),
      elapsedMicros: dco_decode_u_64(arr[5]),
    );
  }

  @protected
  RustScriptDiagnostic dco_decode_rust_script_diagnostic(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return RustScriptDiagnostic(
      severity: dco_decode_String(arr[0]),
      message: dco_decode_String(arr[1]),
      fileName: dco_decode_String(arr[2]),
      sourceLine: dco_decode_u_32(arr[3]),
    );
  }

  @protected
  RustScriptLabel dco_decode_rust_script_label(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return RustScriptLabel(
      label: dco_decode_String(arr[0]),
      fileName: dco_decode_String(arr[1]),
      sourceLine: dco_decode_u_32(arr[2]),
    );
  }

  @protected
  RustScriptReference dco_decode_rust_script_reference(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return RustScriptReference(
      kind: dco_decode_String(arr[0]),
      value: dco_decode_String(arr[1]),
      fileName: dco_decode_String(arr[2]),
      sourceLine: dco_decode_u_32(arr[3]),
    );
  }

  @protected
  RustScriptSource dco_decode_rust_script_source(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return RustScriptSource(
      fileName: dco_decode_String(arr[0]),
      content: dco_decode_String(arr[1]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  Map<String, bool> sse_decode_Map_String_bool_None(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_record_string_bool(deserializer);
    return Map.fromEntries(inner.map((e) => MapEntry(e.$1, e.$2)));
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_bool(deserializer));
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_i_32_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getInt32List(len_);
  }

  @protected
  Int32List sse_decode_list_prim_i_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getInt32List(len_);
  }

  @protected
  Int64List sse_decode_list_prim_i_64_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getInt64List(len_);
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<(String, bool)> sse_decode_list_record_string_bool(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(String, bool)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_record_string_bool(deserializer));
    }
    return ans_;
  }

  @protected
  List<RustAssetEntry> sse_decode_list_rust_asset_entry(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RustAssetEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_rust_asset_entry(deserializer));
    }
    return ans_;
  }

  @protected
  List<RustImageMetadata> sse_decode_list_rust_image_metadata(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RustImageMetadata>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_rust_image_metadata(deserializer));
    }
    return ans_;
  }

  @protected
  List<RustPackEntry> sse_decode_list_rust_pack_entry(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RustPackEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_rust_pack_entry(deserializer));
    }
    return ans_;
  }

  @protected
  List<RustRuntimeChoice> sse_decode_list_rust_runtime_choice(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RustRuntimeChoice>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_rust_runtime_choice(deserializer));
    }
    return ans_;
  }

  @protected
  List<RustRuntimeFlowNode> sse_decode_list_rust_runtime_flow_node(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RustRuntimeFlowNode>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_rust_runtime_flow_node(deserializer));
    }
    return ans_;
  }

  @protected
  List<RustRuntimeLabelIndex> sse_decode_list_rust_runtime_label_index(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RustRuntimeLabelIndex>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_rust_runtime_label_index(deserializer));
    }
    return ans_;
  }

  @protected
  List<RustRuntimeNode> sse_decode_list_rust_runtime_node(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RustRuntimeNode>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_rust_runtime_node(deserializer));
    }
    return ans_;
  }

  @protected
  List<RustRuntimePrompt> sse_decode_list_rust_runtime_prompt(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RustRuntimePrompt>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_rust_runtime_prompt(deserializer));
    }
    return ans_;
  }

  @protected
  List<RustSaveHeader> sse_decode_list_rust_save_header(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RustSaveHeader>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_rust_save_header(deserializer));
    }
    return ans_;
  }

  @protected
  List<RustScriptDiagnostic> sse_decode_list_rust_script_diagnostic(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RustScriptDiagnostic>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_rust_script_diagnostic(deserializer));
    }
    return ans_;
  }

  @protected
  List<RustScriptLabel> sse_decode_list_rust_script_label(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RustScriptLabel>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_rust_script_label(deserializer));
    }
    return ans_;
  }

  @protected
  List<RustScriptReference> sse_decode_list_rust_script_reference(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RustScriptReference>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_rust_script_reference(deserializer));
    }
    return ans_;
  }

  @protected
  List<RustScriptSource> sse_decode_list_rust_script_source(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RustScriptSource>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_rust_script_source(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_bool(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  (String, bool) sse_decode_record_string_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_String(deserializer);
    var var_field1 = sse_decode_bool(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  RustAssetCatalog sse_decode_rust_asset_catalog(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_rootPath = sse_decode_String(deserializer);
    var var_entries = sse_decode_list_rust_asset_entry(deserializer);
    var var_elapsedMicros = sse_decode_u_64(deserializer);
    return RustAssetCatalog(
      rootPath: var_rootPath,
      entries: var_entries,
      elapsedMicros: var_elapsedMicros,
    );
  }

  @protected
  RustAssetEntry sse_decode_rust_asset_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_relativePath = sse_decode_String(deserializer);
    var var_absolutePath = sse_decode_String(deserializer);
    var var_fileName = sse_decode_String(deserializer);
    var var_stem = sse_decode_String(deserializer);
    var var_extension_ = sse_decode_String(deserializer);
    var var_size = sse_decode_u_64(deserializer);
    var var_modifiedMillis = sse_decode_i_64(deserializer);
    return RustAssetEntry(
      relativePath: var_relativePath,
      absolutePath: var_absolutePath,
      fileName: var_fileName,
      stem: var_stem,
      extension_: var_extension_,
      size: var_size,
      modifiedMillis: var_modifiedMillis,
    );
  }

  @protected
  RustDecodedSave sse_decode_rust_decoded_save(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_metadata = sse_decode_rust_save_metadata(deserializer);
    var var_data = sse_decode_list_prim_u_8_strict(deserializer);
    return RustDecodedSave(metadata: var_metadata, data: var_data);
  }

  @protected
  RustImageMetadata sse_decode_rust_image_metadata(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_path = sse_decode_String(deserializer);
    var var_width = sse_decode_u_32(deserializer);
    var var_height = sse_decode_u_32(deserializer);
    var var_decodedRgbaBytes = sse_decode_u_64(deserializer);
    var var_fileBytes = sse_decode_u_64(deserializer);
    var var_format = sse_decode_String(deserializer);
    var var_error = sse_decode_opt_String(deserializer);
    return RustImageMetadata(
      path: var_path,
      width: var_width,
      height: var_height,
      decodedRgbaBytes: var_decodedRgbaBytes,
      fileBytes: var_fileBytes,
      format: var_format,
      error: var_error,
    );
  }

  @protected
  RustMenuSeekResult sse_decode_rust_menu_seek_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_found = sse_decode_bool(deserializer);
    var var_menuIndex = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_prompts = sse_decode_list_rust_runtime_prompt(deserializer);
    var var_visited = sse_decode_u_32(deserializer);
    return RustMenuSeekResult(
      found: var_found,
      menuIndex: var_menuIndex,
      prompts: var_prompts,
      visited: var_visited,
    );
  }

  @protected
  RustPackCatalog sse_decode_rust_pack_catalog(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_handle = sse_decode_u_64(deserializer);
    var var_path = sse_decode_String(deserializer);
    var var_entries = sse_decode_list_rust_pack_entry(deserializer);
    return RustPackCatalog(
      handle: var_handle,
      path: var_path,
      entries: var_entries,
    );
  }

  @protected
  RustPackEntry sse_decode_rust_pack_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_path = sse_decode_String(deserializer);
    var var_offset = sse_decode_u_64(deserializer);
    var var_length = sse_decode_u_64(deserializer);
    var var_text = sse_decode_bool(deserializer);
    var var_sha256 = sse_decode_opt_String(deserializer);
    return RustPackEntry(
      path: var_path,
      offset: var_offset,
      length: var_length,
      text: var_text,
      sha256: var_sha256,
    );
  }

  @protected
  RustReadStateSnapshot sse_decode_rust_read_state_snapshot(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_handle = sse_decode_u_64(deserializer);
    var var_stableHashes = sse_decode_list_prim_i_64_strict(deserializer);
    var var_legacyHashes = sse_decode_list_prim_i_32_strict(deserializer);
    var var_migratedLegacyFile = sse_decode_bool(deserializer);
    return RustReadStateSnapshot(
      handle: var_handle,
      stableHashes: var_stableHashes,
      legacyHashes: var_legacyHashes,
      migratedLegacyFile: var_migratedLegacyFile,
    );
  }

  @protected
  RustRuntimeChoice sse_decode_rust_runtime_choice(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_text = sse_decode_String(deserializer);
    var var_targetLabel = sse_decode_String(deserializer);
    return RustRuntimeChoice(text: var_text, targetLabel: var_targetLabel);
  }

  @protected
  RustRuntimeFlowNode sse_decode_rust_runtime_flow_node(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_label = sse_decode_String(deserializer);
    var var_kind = sse_decode_String(deserializer);
    var var_displayName = sse_decode_String(deserializer);
    var var_scriptIndex = sse_decode_u_32(deserializer);
    var var_chapterName = sse_decode_opt_String(deserializer);
    var var_parentId = sse_decode_opt_String(deserializer);
    var var_childIds = sse_decode_list_String(deserializer);
    var var_branchText = sse_decode_opt_String(deserializer);
    var var_parentIds = sse_decode_list_String(deserializer);
    return RustRuntimeFlowNode(
      id: var_id,
      label: var_label,
      kind: var_kind,
      displayName: var_displayName,
      scriptIndex: var_scriptIndex,
      chapterName: var_chapterName,
      parentId: var_parentId,
      childIds: var_childIds,
      branchText: var_branchText,
      parentIds: var_parentIds,
    );
  }

  @protected
  RustRuntimeIndex sse_decode_rust_runtime_index(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_handle = sse_decode_u_64(deserializer);
    var var_labels = sse_decode_list_rust_runtime_label_index(deserializer);
    var var_flowNodes = sse_decode_list_rust_runtime_flow_node(deserializer);
    var var_rootIds = sse_decode_list_String(deserializer);
    var var_compactBytes = sse_decode_u_64(deserializer);
    var var_elapsedMicros = sse_decode_u_64(deserializer);
    var var_conditionVariables = sse_decode_list_String(deserializer);
    return RustRuntimeIndex(
      handle: var_handle,
      labels: var_labels,
      flowNodes: var_flowNodes,
      rootIds: var_rootIds,
      compactBytes: var_compactBytes,
      elapsedMicros: var_elapsedMicros,
      conditionVariables: var_conditionVariables,
    );
  }

  @protected
  RustRuntimeLabelIndex sse_decode_rust_runtime_label_index(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_label = sse_decode_String(deserializer);
    var var_scriptIndex = sse_decode_u_32(deserializer);
    return RustRuntimeLabelIndex(
      label: var_label,
      scriptIndex: var_scriptIndex,
    );
  }

  @protected
  RustRuntimeNode sse_decode_rust_runtime_node(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_scriptIndex = sse_decode_u_32(deserializer);
    var var_kind = sse_decode_String(deserializer);
    var var_value = sse_decode_opt_String(deserializer);
    var var_secondary = sse_decode_opt_String(deserializer);
    var var_dialogueTag = sse_decode_opt_String(deserializer);
    var var_sourceFile = sse_decode_opt_String(deserializer);
    var var_sourceLine = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_conditionVariable = sse_decode_opt_String(deserializer);
    var var_conditionValue = sse_decode_opt_box_autoadd_bool(deserializer);
    var var_choices = sse_decode_list_rust_runtime_choice(deserializer);
    return RustRuntimeNode(
      scriptIndex: var_scriptIndex,
      kind: var_kind,
      value: var_value,
      secondary: var_secondary,
      dialogueTag: var_dialogueTag,
      sourceFile: var_sourceFile,
      sourceLine: var_sourceLine,
      conditionVariable: var_conditionVariable,
      conditionValue: var_conditionValue,
      choices: var_choices,
    );
  }

  @protected
  RustRuntimePrompt sse_decode_rust_runtime_prompt(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_dialogue = sse_decode_String(deserializer);
    var var_speaker = sse_decode_opt_String(deserializer);
    var var_dialogueTag = sse_decode_opt_String(deserializer);
    var var_scriptIndex = sse_decode_u_32(deserializer);
    var var_sourceFile = sse_decode_opt_String(deserializer);
    var var_sourceLine = sse_decode_opt_box_autoadd_u_32(deserializer);
    return RustRuntimePrompt(
      dialogue: var_dialogue,
      speaker: var_speaker,
      dialogueTag: var_dialogueTag,
      scriptIndex: var_scriptIndex,
      sourceFile: var_sourceFile,
      sourceLine: var_sourceLine,
    );
  }

  @protected
  RustSaveHeader sse_decode_rust_save_header(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_64(deserializer);
    var var_version = sse_decode_i_32(deserializer);
    var var_saveTimeMillis = sse_decode_i_64(deserializer);
    var var_currentScript = sse_decode_String(deserializer);
    var var_dialoguePreview = sse_decode_String(deserializer);
    var var_filePath = sse_decode_String(deserializer);
    var var_screenshotOffset = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_screenshotLength = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_isLocked = sse_decode_bool(deserializer);
    var var_scriptIndex = sse_decode_i_32(deserializer);
    var var_previewKind = sse_decode_String(deserializer);
    var var_previewSpeaker = sse_decode_opt_String(deserializer);
    var var_previewText = sse_decode_opt_String(deserializer);
    var var_previewChoices = sse_decode_list_String(deserializer);
    return RustSaveHeader(
      id: var_id,
      version: var_version,
      saveTimeMillis: var_saveTimeMillis,
      currentScript: var_currentScript,
      dialoguePreview: var_dialoguePreview,
      filePath: var_filePath,
      screenshotOffset: var_screenshotOffset,
      screenshotLength: var_screenshotLength,
      isLocked: var_isLocked,
      scriptIndex: var_scriptIndex,
      previewKind: var_previewKind,
      previewSpeaker: var_previewSpeaker,
      previewText: var_previewText,
      previewChoices: var_previewChoices,
    );
  }

  @protected
  RustSaveHeaderScan sse_decode_rust_save_header_scan(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_slots = sse_decode_list_rust_save_header(deserializer);
    var var_invalidFiles = sse_decode_list_String(deserializer);
    var var_elapsedMicros = sse_decode_u_64(deserializer);
    return RustSaveHeaderScan(
      slots: var_slots,
      invalidFiles: var_invalidFiles,
      elapsedMicros: var_elapsedMicros,
    );
  }

  @protected
  RustSaveMetadata sse_decode_rust_save_metadata(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_version = sse_decode_i_32(deserializer);
    var var_id = sse_decode_i_64(deserializer);
    var var_saveTimeMillis = sse_decode_i_64(deserializer);
    var var_currentScript = sse_decode_String(deserializer);
    var var_dialoguePreview = sse_decode_String(deserializer);
    var var_screenshotOffset = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_screenshotLength = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_isLocked = sse_decode_bool(deserializer);
    var var_scriptIndex = sse_decode_i_32(deserializer);
    return RustSaveMetadata(
      version: var_version,
      id: var_id,
      saveTimeMillis: var_saveTimeMillis,
      currentScript: var_currentScript,
      dialoguePreview: var_dialoguePreview,
      screenshotOffset: var_screenshotOffset,
      screenshotLength: var_screenshotLength,
      isLocked: var_isLocked,
      scriptIndex: var_scriptIndex,
    );
  }

  @protected
  RustScriptCompileResult sse_decode_rust_script_compile_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_mergedSource = sse_decode_String(deserializer);
    var var_orderedFiles = sse_decode_list_String(deserializer);
    var var_labels = sse_decode_list_rust_script_label(deserializer);
    var var_references = sse_decode_list_rust_script_reference(deserializer);
    var var_diagnostics = sse_decode_list_rust_script_diagnostic(deserializer);
    var var_elapsedMicros = sse_decode_u_64(deserializer);
    return RustScriptCompileResult(
      mergedSource: var_mergedSource,
      orderedFiles: var_orderedFiles,
      labels: var_labels,
      references: var_references,
      diagnostics: var_diagnostics,
      elapsedMicros: var_elapsedMicros,
    );
  }

  @protected
  RustScriptDiagnostic sse_decode_rust_script_diagnostic(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_severity = sse_decode_String(deserializer);
    var var_message = sse_decode_String(deserializer);
    var var_fileName = sse_decode_String(deserializer);
    var var_sourceLine = sse_decode_u_32(deserializer);
    return RustScriptDiagnostic(
      severity: var_severity,
      message: var_message,
      fileName: var_fileName,
      sourceLine: var_sourceLine,
    );
  }

  @protected
  RustScriptLabel sse_decode_rust_script_label(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_label = sse_decode_String(deserializer);
    var var_fileName = sse_decode_String(deserializer);
    var var_sourceLine = sse_decode_u_32(deserializer);
    return RustScriptLabel(
      label: var_label,
      fileName: var_fileName,
      sourceLine: var_sourceLine,
    );
  }

  @protected
  RustScriptReference sse_decode_rust_script_reference(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_String(deserializer);
    var var_value = sse_decode_String(deserializer);
    var var_fileName = sse_decode_String(deserializer);
    var var_sourceLine = sse_decode_u_32(deserializer);
    return RustScriptReference(
      kind: var_kind,
      value: var_value,
      fileName: var_fileName,
      sourceLine: var_sourceLine,
    );
  }

  @protected
  RustScriptSource sse_decode_rust_script_source(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_fileName = sse_decode_String(deserializer);
    var var_content = sse_decode_String(deserializer);
    return RustScriptSource(fileName: var_fileName, content: var_content);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_Map_String_bool_None(
    Map<String, bool> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_record_string_bool(
      self.entries.map((e) => (e.key, e.value)).toList(),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_i_32_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putInt32List(
      self is Int32List ? self : Int32List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_i_32_strict(
    Int32List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putInt32List(self);
  }

  @protected
  void sse_encode_list_prim_i_64_strict(
    Int64List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putInt64List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_record_string_bool(
    List<(String, bool)> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_string_bool(item, serializer);
    }
  }

  @protected
  void sse_encode_list_rust_asset_entry(
    List<RustAssetEntry> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_rust_asset_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_list_rust_image_metadata(
    List<RustImageMetadata> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_rust_image_metadata(item, serializer);
    }
  }

  @protected
  void sse_encode_list_rust_pack_entry(
    List<RustPackEntry> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_rust_pack_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_list_rust_runtime_choice(
    List<RustRuntimeChoice> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_rust_runtime_choice(item, serializer);
    }
  }

  @protected
  void sse_encode_list_rust_runtime_flow_node(
    List<RustRuntimeFlowNode> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_rust_runtime_flow_node(item, serializer);
    }
  }

  @protected
  void sse_encode_list_rust_runtime_label_index(
    List<RustRuntimeLabelIndex> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_rust_runtime_label_index(item, serializer);
    }
  }

  @protected
  void sse_encode_list_rust_runtime_node(
    List<RustRuntimeNode> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_rust_runtime_node(item, serializer);
    }
  }

  @protected
  void sse_encode_list_rust_runtime_prompt(
    List<RustRuntimePrompt> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_rust_runtime_prompt(item, serializer);
    }
  }

  @protected
  void sse_encode_list_rust_save_header(
    List<RustSaveHeader> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_rust_save_header(item, serializer);
    }
  }

  @protected
  void sse_encode_list_rust_script_diagnostic(
    List<RustScriptDiagnostic> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_rust_script_diagnostic(item, serializer);
    }
  }

  @protected
  void sse_encode_list_rust_script_label(
    List<RustScriptLabel> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_rust_script_label(item, serializer);
    }
  }

  @protected
  void sse_encode_list_rust_script_reference(
    List<RustScriptReference> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_rust_script_reference(item, serializer);
    }
  }

  @protected
  void sse_encode_list_rust_script_source(
    List<RustScriptSource> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_rust_script_source(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_bool(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_record_string_bool(
    (String, bool) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.$1, serializer);
    sse_encode_bool(self.$2, serializer);
  }

  @protected
  void sse_encode_rust_asset_catalog(
    RustAssetCatalog self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.rootPath, serializer);
    sse_encode_list_rust_asset_entry(self.entries, serializer);
    sse_encode_u_64(self.elapsedMicros, serializer);
  }

  @protected
  void sse_encode_rust_asset_entry(
    RustAssetEntry self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.relativePath, serializer);
    sse_encode_String(self.absolutePath, serializer);
    sse_encode_String(self.fileName, serializer);
    sse_encode_String(self.stem, serializer);
    sse_encode_String(self.extension_, serializer);
    sse_encode_u_64(self.size, serializer);
    sse_encode_i_64(self.modifiedMillis, serializer);
  }

  @protected
  void sse_encode_rust_decoded_save(
    RustDecodedSave self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_rust_save_metadata(self.metadata, serializer);
    sse_encode_list_prim_u_8_strict(self.data, serializer);
  }

  @protected
  void sse_encode_rust_image_metadata(
    RustImageMetadata self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.path, serializer);
    sse_encode_u_32(self.width, serializer);
    sse_encode_u_32(self.height, serializer);
    sse_encode_u_64(self.decodedRgbaBytes, serializer);
    sse_encode_u_64(self.fileBytes, serializer);
    sse_encode_String(self.format, serializer);
    sse_encode_opt_String(self.error, serializer);
  }

  @protected
  void sse_encode_rust_menu_seek_result(
    RustMenuSeekResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.found, serializer);
    sse_encode_opt_box_autoadd_u_32(self.menuIndex, serializer);
    sse_encode_list_rust_runtime_prompt(self.prompts, serializer);
    sse_encode_u_32(self.visited, serializer);
  }

  @protected
  void sse_encode_rust_pack_catalog(
    RustPackCatalog self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.handle, serializer);
    sse_encode_String(self.path, serializer);
    sse_encode_list_rust_pack_entry(self.entries, serializer);
  }

  @protected
  void sse_encode_rust_pack_entry(
    RustPackEntry self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.path, serializer);
    sse_encode_u_64(self.offset, serializer);
    sse_encode_u_64(self.length, serializer);
    sse_encode_bool(self.text, serializer);
    sse_encode_opt_String(self.sha256, serializer);
  }

  @protected
  void sse_encode_rust_read_state_snapshot(
    RustReadStateSnapshot self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.handle, serializer);
    sse_encode_list_prim_i_64_strict(self.stableHashes, serializer);
    sse_encode_list_prim_i_32_strict(self.legacyHashes, serializer);
    sse_encode_bool(self.migratedLegacyFile, serializer);
  }

  @protected
  void sse_encode_rust_runtime_choice(
    RustRuntimeChoice self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.text, serializer);
    sse_encode_String(self.targetLabel, serializer);
  }

  @protected
  void sse_encode_rust_runtime_flow_node(
    RustRuntimeFlowNode self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.label, serializer);
    sse_encode_String(self.kind, serializer);
    sse_encode_String(self.displayName, serializer);
    sse_encode_u_32(self.scriptIndex, serializer);
    sse_encode_opt_String(self.chapterName, serializer);
    sse_encode_opt_String(self.parentId, serializer);
    sse_encode_list_String(self.childIds, serializer);
    sse_encode_opt_String(self.branchText, serializer);
    sse_encode_list_String(self.parentIds, serializer);
  }

  @protected
  void sse_encode_rust_runtime_index(
    RustRuntimeIndex self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.handle, serializer);
    sse_encode_list_rust_runtime_label_index(self.labels, serializer);
    sse_encode_list_rust_runtime_flow_node(self.flowNodes, serializer);
    sse_encode_list_String(self.rootIds, serializer);
    sse_encode_u_64(self.compactBytes, serializer);
    sse_encode_u_64(self.elapsedMicros, serializer);
    sse_encode_list_String(self.conditionVariables, serializer);
  }

  @protected
  void sse_encode_rust_runtime_label_index(
    RustRuntimeLabelIndex self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.label, serializer);
    sse_encode_u_32(self.scriptIndex, serializer);
  }

  @protected
  void sse_encode_rust_runtime_node(
    RustRuntimeNode self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.scriptIndex, serializer);
    sse_encode_String(self.kind, serializer);
    sse_encode_opt_String(self.value, serializer);
    sse_encode_opt_String(self.secondary, serializer);
    sse_encode_opt_String(self.dialogueTag, serializer);
    sse_encode_opt_String(self.sourceFile, serializer);
    sse_encode_opt_box_autoadd_u_32(self.sourceLine, serializer);
    sse_encode_opt_String(self.conditionVariable, serializer);
    sse_encode_opt_box_autoadd_bool(self.conditionValue, serializer);
    sse_encode_list_rust_runtime_choice(self.choices, serializer);
  }

  @protected
  void sse_encode_rust_runtime_prompt(
    RustRuntimePrompt self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.dialogue, serializer);
    sse_encode_opt_String(self.speaker, serializer);
    sse_encode_opt_String(self.dialogueTag, serializer);
    sse_encode_u_32(self.scriptIndex, serializer);
    sse_encode_opt_String(self.sourceFile, serializer);
    sse_encode_opt_box_autoadd_u_32(self.sourceLine, serializer);
  }

  @protected
  void sse_encode_rust_save_header(
    RustSaveHeader self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.id, serializer);
    sse_encode_i_32(self.version, serializer);
    sse_encode_i_64(self.saveTimeMillis, serializer);
    sse_encode_String(self.currentScript, serializer);
    sse_encode_String(self.dialoguePreview, serializer);
    sse_encode_String(self.filePath, serializer);
    sse_encode_opt_box_autoadd_i_64(self.screenshotOffset, serializer);
    sse_encode_opt_box_autoadd_i_64(self.screenshotLength, serializer);
    sse_encode_bool(self.isLocked, serializer);
    sse_encode_i_32(self.scriptIndex, serializer);
    sse_encode_String(self.previewKind, serializer);
    sse_encode_opt_String(self.previewSpeaker, serializer);
    sse_encode_opt_String(self.previewText, serializer);
    sse_encode_list_String(self.previewChoices, serializer);
  }

  @protected
  void sse_encode_rust_save_header_scan(
    RustSaveHeaderScan self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_rust_save_header(self.slots, serializer);
    sse_encode_list_String(self.invalidFiles, serializer);
    sse_encode_u_64(self.elapsedMicros, serializer);
  }

  @protected
  void sse_encode_rust_save_metadata(
    RustSaveMetadata self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.version, serializer);
    sse_encode_i_64(self.id, serializer);
    sse_encode_i_64(self.saveTimeMillis, serializer);
    sse_encode_String(self.currentScript, serializer);
    sse_encode_String(self.dialoguePreview, serializer);
    sse_encode_opt_box_autoadd_u_64(self.screenshotOffset, serializer);
    sse_encode_opt_box_autoadd_u_64(self.screenshotLength, serializer);
    sse_encode_bool(self.isLocked, serializer);
    sse_encode_i_32(self.scriptIndex, serializer);
  }

  @protected
  void sse_encode_rust_script_compile_result(
    RustScriptCompileResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.mergedSource, serializer);
    sse_encode_list_String(self.orderedFiles, serializer);
    sse_encode_list_rust_script_label(self.labels, serializer);
    sse_encode_list_rust_script_reference(self.references, serializer);
    sse_encode_list_rust_script_diagnostic(self.diagnostics, serializer);
    sse_encode_u_64(self.elapsedMicros, serializer);
  }

  @protected
  void sse_encode_rust_script_diagnostic(
    RustScriptDiagnostic self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.severity, serializer);
    sse_encode_String(self.message, serializer);
    sse_encode_String(self.fileName, serializer);
    sse_encode_u_32(self.sourceLine, serializer);
  }

  @protected
  void sse_encode_rust_script_label(
    RustScriptLabel self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.label, serializer);
    sse_encode_String(self.fileName, serializer);
    sse_encode_u_32(self.sourceLine, serializer);
  }

  @protected
  void sse_encode_rust_script_reference(
    RustScriptReference self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.kind, serializer);
    sse_encode_String(self.value, serializer);
    sse_encode_String(self.fileName, serializer);
    sse_encode_u_32(self.sourceLine, serializer);
  }

  @protected
  void sse_encode_rust_script_source(
    RustScriptSource self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.fileName, serializer);
    sse_encode_String(self.content, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
